### PR TITLE
Fix for latest and added CUE4Parse as submodule

### PR DESCRIPTION
**Pull request by GhostScissors**

### CODE REVIEW

**Comment by loolo761** [comment]
Works ty

**Comment by FirexLeakszz** [comment]
I know you've added a few things to the program to make it work properly, but it ended up giving the same error.

**Comment by GhostScissors** [comment]
I don't know what issue are you having but it clearly works on my end image_2023-11-19_215413637

**Comment by FirexLeakszz** [comment]
Can you send me your program? I couldn't fix it, discord: firexleaks 

please

> I don't know what issue are you having but it clearly works on my end image_2023-11-19_215413637

**Comment by FirexLeakszz** [comment]
imagem_2023-11-20_201501467

I downloaded the recent version you updated and I still get this fucking error

**Comment by FirexLeakszz** [comment]
image


says this is the error

**Pull request merged**
